name: dbt_run_streamline_chainhead
run-name: dbt_run_streamline_chainhead

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@main
    with:
      command_name: Run Chainhead Models
      command: |
        dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True,"MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_PRODUCER_BATCH_SIZE":4800,"MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_WORKER_BATCH_SIZE":600,"MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_ASYNC_CONCURRENT_REQUESTS":50,"MAIN_SL_RECEIPTS_REALTIME_PRODUCER_BATCH_SIZE":4800,"MAIN_SL_RECEIPTS_REALTIME_WORKER_BATCH_SIZE":600,"MAIN_SL_RECEIPTS_REALTIME_ASYNC_CONCURRENT_REQUESTS":50,"MAIN_SL_TRACES_REALTIME_PRODUCER_BATCH_SIZE":4800,"MAIN_SL_TRACES_REALTIME_WORKER_BATCH_SIZE":600,"MAIN_SL_TRACES_REALTIME_ASYNC_CONCURRENT_REQUESTS":50,"MAIN_SL_CONFIRM_BLOCKS_REALTIME_PRODUCER_BATCH_SIZE":4800,"MAIN_SL_CONFIRM_BLOCKS_REALTIME_WORKER_BATCH_SIZE":600,"MAIN_SL_CONFIRM_BLOCKS_REALTIME_ASYNC_CONCURRENT_REQUESTS":50}' -m "fsc_evm,tag:chainhead" "fsc_evm,tag:streamline,tag:core,tag:complete" "fsc_evm,tag:streamline,tag:core,tag:realtime" --exclude "fsc_evm,tag:receipts_by_hash"
        dbt test -m "fsc_evm,tag:chainhead"
    secrets: inherit