version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'BSC' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: ez_hourly_token_prices
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
      - name: ez_hourly_token_prices
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables:
      - name: node_mapping
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'BSC' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: apis_keys
      - name: token_prices_priority_hourly
      - name: token_prices_all_providers_hourly
      - name: asset_metadata_priority
      - name: asset_metadata_all_providers
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "BSC_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "BSC" }}
    tables:
      - name: blocks
      - name: transactions
      - name: receipts
      - name: traces
      - name: decoded_logs
      - name: confirm_blocks
      - name: token_balances
      - name: bnb_balances
  - name: bsc_silver
    database: bsc
    schema: silver
    tables:
      - name: verified_abis
  - name: bsc_bronze_api
    database: bsc
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: bsc
    schema: github_actions
    tables:
      - name: workflows