version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'BSC' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'BSC' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ var('GLOBAL_PROD_DB_NAME') ~ ('_dev' if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else '') }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: traces
      - name: decoded_logs
      - name: confirm_blocks
      - name: blocks_v2
      - name: transactions_v2
      - name: receipts_v2
      - name: traces_v2
      - name: confirm_blocks_v2
      - name: decoded_logs_v2
      - name: token_balances
      - name: bnb_balances
      - name: flat_traces
  - name: bsc_silver
    database: bsc
    schema: silver
    tables:
      - name: verified_abis
      - name: overflowed_traces
      - name: overflowed_traces2
      - name: overflowed_receipts
      - name: overflowed_logs
  - name: bsc_bronze_api
    database: bsc
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: bsc
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
  - name: bsc_silver_dev
    database: bsc_dev
    schema: silver
    tables:
      - name: overflowed_traces2
  - name: bsc_gold
    database: "{{ 'bsc' if target.database == 'BSC' else 'bsc_dev' }}"
    schema: core
    tables:
      - name: fact_traces
