version: 2

sources:
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
      - name: ez_hourly_prices
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables:
      - name: node_mapping
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: apis_keys
      - name: token_prices_priority_hourly
      - name: asset_metadata_priority
      - name: number_sequence
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "BSC_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "BSC" }}
    tables:
      - name: blocks
      - name: transactions
      - name: receipts
      - name: traces
      - name: decoded_logs
      - name: confirm_blocks
  - name: bsc_silver
    database: bsc
    schema: silver
    tables:
      - name: verified_abis
  - name: bsc_bronze_api
    database: bsc
    schema: bronze_api
    tables:
      - name: contract_abis